//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLVT.Helper.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chua Ton Tai.
        /// </summary>
        public static string ChuaTonTai {
            get {
                return ResourceManager.GetString("ChuaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da Ton Tai.
        /// </summary>
        public static string DaTonTai {
            get {
                return ResourceManager.GetString("DaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loi khi nhap du lieu, khong dung dinh dang!.
        /// </summary>
        public static string Err {
            get {
                return ResourceManager.GetString("Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phai nhap so nguyen hop le:.
        /// </summary>
        public static string ErrINT {
            get {
                return ResourceManager.GetString("ErrINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da het hang. Can nhap them!.
        /// </summary>
        public static string HetHang {
            get {
                return ResourceManager.GetString("HetHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ngay thang:.
        /// </summary>
        public static string InputDT {
            get {
                return ResourceManager.GetString("InputDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so nguyen:.
        /// </summary>
        public static string InputINT {
            get {
                return ResourceManager.GetString("InputINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap cac ky tu:.
        /// </summary>
        public static string InputSTR {
            get {
                return ResourceManager.GetString("InputSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong Du Hang de xuat!.
        /// </summary>
        public static string KhongDuHang {
            get {
                return ResourceManager.GetString("KhongDuHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuc hien thanh cong!.
        /// </summary>
        public static string ThanhCong {
            get {
                return ResourceManager.GetString("ThanhCong", resourceCulture);
            }
        }
    }
}
